import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Logo } from "./Logo";
import { Github, Twitter, Linkedin } from "lucide-react";
export function SiteFooter() {
    return (_jsx("footer", { className: "border-t border-border bg-card", children: _jsxs("div", { className: "mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8", children: [_jsxs("div", { className: "grid gap-10 md:grid-cols-4", children: [_jsxs("div", { className: "space-y-4", children: [_jsx(Logo, {}), _jsx("p", { className: "text-sm leading-relaxed text-muted-foreground", children: "Turn raw data into intelligent insights \u2014 automatically." }), _jsxs("div", { className: "flex gap-2", children: [_jsx("a", { href: "#", "aria-label": "Twitter", className: "rounded-md border border-border bg-background p-2 text-muted-foreground transition-smooth hover:border-primary/40 hover:text-foreground", children: _jsx(Twitter, { className: "h-4 w-4" }) }), _jsx("a", { href: "#", "aria-label": "GitHub", className: "rounded-md border border-border bg-background p-2 text-muted-foreground transition-smooth hover:border-primary/40 hover:text-foreground", children: _jsx(Github, { className: "h-4 w-4" }) }), _jsx("a", { href: "#", "aria-label": "LinkedIn", className: "rounded-md border border-border bg-background p-2 text-muted-foreground transition-smooth hover:border-primary/40 hover:text-foreground", children: _jsx(Linkedin, { className: "h-4 w-4" }) })] })] }), [
                            { title: "Product", links: ["Features", "Pricing", "Changelog", "Roadmap"] },
                            { title: "Company", links: ["About", "Blog", "Careers", "Contact"] },
                            { title: "Resources", links: ["Docs", "API", "Community", "Status"] },
                        ].map((col) => (_jsxs("div", { children: [_jsx("h4", { className: "mb-3 text-sm font-semibold", children: col.title }), _jsx("ul", { className: "space-y-2", children: col.links.map((l) => (_jsx("li", { children: _jsx("a", { href: "#", className: "text-sm text-muted-foreground transition-smooth hover:text-foreground", children: l }) }, l))) })] }, col.title)))] }), _jsxs("div", { className: "mt-10 flex flex-col items-center justify-between gap-3 border-t border-border pt-6 text-xs text-muted-foreground sm:flex-row", children: [_jsxs("span", { children: ["\u00A9 ", new Date().getFullYear(), " AutoInsight AI. All rights reserved."] }), _jsxs("div", { className: "flex gap-5", children: [_jsx("a", { href: "#", className: "hover:text-foreground", children: "Privacy" }), _jsx("a", { href: "#", className: "hover:text-foreground", children: "Terms" }), _jsx("a", { href: "#", className: "hover:text-foreground", children: "Security" })] })] })] }) }));
}
