/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as VisualizationsRouteImport } from './routes/visualizations';
import { Route as UploadRouteImport } from './routes/upload';
import { Route as SignupRouteImport } from './routes/signup';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as ReportsRouteImport } from './routes/reports';
import { Route as PredictionsRouteImport } from './routes/predictions';
import { Route as LoginRouteImport } from './routes/login';
import { Route as InsightsRouteImport } from './routes/insights';
import { Route as DashboardRouteImport } from './routes/dashboard';
import { Route as CleaningRouteImport } from './routes/cleaning';
import { Route as ChatRouteImport } from './routes/chat';
import { Route as IndexRouteImport } from './routes/index';
const VisualizationsRoute = VisualizationsRouteImport.update({
    id: '/visualizations',
    path: '/visualizations',
    getParentRoute: () => rootRouteImport,
});
const UploadRoute = UploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => rootRouteImport,
});
const SignupRoute = SignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => rootRouteImport,
});
const SettingsRoute = SettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => rootRouteImport,
});
const ReportsRoute = ReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => rootRouteImport,
});
const PredictionsRoute = PredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
});
const InsightsRoute = InsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => rootRouteImport,
});
const DashboardRoute = DashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => rootRouteImport,
});
const CleaningRoute = CleaningRouteImport.update({
    id: '/cleaning',
    path: '/cleaning',
    getParentRoute: () => rootRouteImport,
});
const ChatRoute = ChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    ChatRoute: ChatRoute,
    CleaningRoute: CleaningRoute,
    DashboardRoute: DashboardRoute,
    InsightsRoute: InsightsRoute,
    LoginRoute: LoginRoute,
    PredictionsRoute: PredictionsRoute,
    ReportsRoute: ReportsRoute,
    SettingsRoute: SettingsRoute,
    SignupRoute: SignupRoute,
    UploadRoute: UploadRoute,
    VisualizationsRoute: VisualizationsRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
